version: '3.9'
services:
  db:
    container_name: postgres_pizzaria_container
    image: postgres:16.2
    restart: always
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_DB: pizzaria
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/pizzaria/postgres_data
